### ISSUE TITLE
No longer working when server includes Message-Authenticator

### ISSUE THREAD

**Issue by sishik1** [vforteli/Flexinets.Radius.Core#14]
Not sure what's going on here, but when getting results via radiusPacketParser.Parse() method, library is unable to properly calculate message authenticator and always throwing 'Invalid Message-Authenticator in packet' error. Happens on FreeRadius v3.0.20 on RHEL. Maybe server implementation of how message-authenticator is generated has changed and now there is a mismatch? This used to work, but not working anymore. Maybe it's related to BlastRADIUS issue?

**Comment by vforteli** [comment]
Could be blastradius related indeed. What kind of packet did this happen with?

**Comment by sishik1** [comment]
> Could be blastradius related indeed. What kind of packet did this happen with?

Happened on Access Request.

**Comment by sishik1** [comment]
> > Could be blastradius related indeed. What kind of packet did this happen with?
> 
> Happened on Access Request.

I should add that it happens after Access Request is sent. BlastRadius fix for the client requires message-authenticator on every request, so I manually 'Message-Authenticator' attribute with zero bytes to client attributes, which then gets filled in GetBytes() method. Server gets the request, doesn't complain that Message-Authenticator is missing, processes the request and sends back Access Accept. It's here when library tries to parse the packet bytes, it throws an error due to Message Authenticator mismatch. I'm really puzzled as to what's wrong here. The packet looks fine, but calculated hash doesn't match the message authenticator hash in the packet.

**Comment by vforteli** [comment]
I think I have a pretty good idea what the issue is. The biggest task is dragging the codebase into 2024 to test it

**Comment by sishik1** [comment]
> I think I have a pretty good idea what the issue is. The biggest task is dragging the codebase into 2024 to test it

Good to hear! Looking at what the BlastRADIUS fix was about, does it have something to do with message-authenticator being now first attribute in the response?

**Comment by sishik1** [comment]
This is really odd. I don't see what could be wrong when generating message authenticator to compare with value in RADIUS packet. The only fix for BlastRADIUS was always including message authenticator in all responses from the server, but the client already handles that, so I'm now really sure what's going on here anymore. Where could the issue be?

**Comment by sishik1** [comment]
> This is really odd. I don't see what could be wrong when generating message authenticator to compare with value in RADIUS packet. The only fix for BlastRADIUS was always including message authenticator in all responses from the server, but the client already handles that, so I'm now really sure what's going on here anymore. Where could the issue be?

I got it! When calculating message authenticator for response, it needs to use original authenticator of the packet in position 4 of the response packet. Probably, need to change Parse() method to pass original authenticator from request and then use that as parameter to CalculateMessageAuthenticator() method, which right now uses null as third argument?

**Comment by vforteli** [comment]
So, finally got around to actually test the server. Seems like it does kinda work when manually adding a Message-Authenticator to response packets with an empty byte[16].

Tried with the test server and set it to respond with:

https://github.com/vforteli/Flexinets.Radius.Core/blob/b7a495b5c367a06ef464b4657a0aa224a97a658a/RadiusTestServer/src/PacketHandler/TestPacketHandler.cs#L36

Log from radclient using -b to require blastradius checks
```
root@6652caa65b66:/# echo "User-Name=user@example.com, User-Password=1234" | radclient -x host.docker.internal:1812 auth somesecret -b
Sent Access-Request Id 19 from 0.0.0.0:53435 to 192.168.5.2:1812 length 74
	User-Name = "user@example.com"
	User-Password = "1234"
	Cleartext-Password = "1234"
Received Access-Accept Id 19 from 192.168.5.2:1812 to 10.4.0.128:53435 length 38
	Message-Authenticator = 0x701df9d5e3dbccaf7f29da6b2cf6209a
```

Now if this should be the responsibility of the packet handler, server or the lower level package is then up for debate 🤔
Now 8 years later the API does seem a bit convoluted and could probably be simplified quite a lot

**Comment by sishik1** [comment]
> So, finally got around to actually test the server. Seems like it does kinda work when manually adding a Message-Authenticator to response packets with an empty byte[16].
> 
> Tried with the test server and set it to respond with:
> 
> https://github.com/vforteli/Flexinets.Radius.Core/blob/b7a495b5c367a06ef464b4657a0aa224a97a658a/RadiusTestServer/src/PacketHandler/TestPacketHandler.cs#L36
> 
> Log from radclient using -b to require blastradius checks
> 
> ```
> root@6652caa65b66:/# echo "User-Name=user@example.com, User-Password=1234" | radclient -x host.docker.internal:1812 auth somesecret -b
> Sent Access-Request Id 19 from 0.0.0.0:53435 to 192.168.5.2:1812 length 74
> 	User-Name = "user@example.com"
> 	User-Password = "1234"
> 	Cleartext-Password = "1234"
> Received Access-Accept Id 19 from 192.168.5.2:1812 to 10.4.0.128:53435 length 38
> 	Message-Authenticator = 0x701df9d5e3dbccaf7f29da6b2cf6209a
> ```
> 
> Now if this should be the responsibility of the packet handler, server or the lower level package is then up for debate 🤔 Now 8 years later the API does seem a bit convoluted and could probably be simplified quite a lot

I think for BlastRadius fix, every RADIUS server that has a fix automatically responds with message authenticator. Prior to the fix, I believe it was optional. But now when parsing packet response, library fails to process bytes due to mismatch on message authenticator. From what I understand, when calculating message authenticator from response, it needs to use original request authenticator. 

Something like this: public IRadiusPacket Parse(byte[] packetBytes, byte[] sharedSecret, byte[] originalRequestAuthenticator) and then inside the method this:
     var calculatedMessageAuthenticator = CalculateMessageAuthenticator(tempPacket, sharedSecret, originalRequestAuthenticator);

Only with the above, I could get the code to process response from my FreeRadius server.

**Comment by vforteli** [comment]
ah that was the other way around compared to my example. Have to try that also then

**Comment by sishik1** [comment]
> ah that was the other way around compared to my example. Have to try that also then

Yes, the issue is from the server to the client. With server always including message authenticator now, there is now mismatch on the message authenticator value since library is not using client message authenticator when calculating response value. When calling Parse() method after getting RADIUS packet from the server, it just needs to pass request packet.Authenticator to the method and use it when calling  CalculateMessageAuthenticator(). Also, client should now always include message-authenticator for all calls. I think it's adding Message-Authenticator attribute only for StatusServer packet code.

**Comment by vforteli** [comment]
ookay the updated version seems to be working nicely with freeradius now. Probably needs some more tests though

**Comment by gm-1024** [comment]
This fix is required also for windows radius NPS. After 2024-10 Cumulative Update for Windows Server 2019 for x64-based Systems (KB5044277) the behaviour is the same as described in this issue.

**Comment by sishik1** [comment]
Looks good now! I will close this issue.

**Comment by gm-1024** [comment]
Nope. This fix has broken windows nps radius before KB5044277 update. If Message-Authenticator is not presented in the package, I got error from check for blast ("No message authenticator found in packet"). Of course I can set _skipBlastRadiusChecks but I don't think that it's a good solution.

**Comment by sishik1** [comment]
> Nope. This fix has broken windows nps radius before KB5044277 update. If Message-Authenticator is not presented in the package, I got error from check for blast ("No message authenticator found in packet"). Of course I can set _skipBlastRadiusChecks but I don't think that it's a good solution.

Yes, but you are supposed to have all servers upgraded to always include Message-Authenticator in the packet. That's a requirement for BlastRADIUS fix. You can use _skipBlastRadiusChecks, but technically, it's not a good idea to skip it.

**Comment by gm-1024** [comment]
I think that _skipBlastRadiusChecks variable should be renamed because it's not a unique behaviour for blast. We must explicitly specify whether we should skip the message-authenticator check and for which types of packets.

**Comment by vforteli** [comment]
Yes, definitely, maybe. 
According to the RFC the message authenticator should also be required with EAP, but that isnt enforced here in the parser now. Technically you could of course do that in the handler instead but I suppose it would make more sense to have that as the responsibility of the lower level parser in this repo.

Anyway, now that I got around to dragging this project into 2024 Ill probably do some more fixes to better cover the RFCs
