### ISSUE TITLE
Attribute "Message-Authenticator" Calculated Incorrectly

### ISSUE THREAD

**Issue by co2chicken** [vforteli/Flexinets.Radius.Core#7]
The "Message-Authenticator" attribute (id 80) is to be calculated using the request-authenticator from the access-request packet. From RFC 2869:

> For Access-Challenge, Access-Accept, and Access-Reject packets, the Message-Authenticator is calculated as follows, using the Request-Authenticator from the Access-Request this packet is in
      reply to:
      Message-Authenticator = HMAC-MD5 (Type, Identifier, Length, Request Authenticator, Attributes)

In `RadiusPacketParser.cs`, lines 341 to 358, this is done in reverse order. First, the request-authenticator is calculated for the current packet, then the message-authenticator is calculated. The change I made so this would work is below. I tested this code against a unifi switch that was using the server to authenticate RADIUS clients.

`            var packetBytesArray = packetBytes.ToArray();

            if (messageAuthenticatorPosition != 0 && packet.RequestAuthenticator?.Length >= 16)
            {
                // have to put requestAuthenticator in for message authenticator
                var packetBytesArrayCopy = packetBytesArray.ToArray();
                Buffer.BlockCopy(packet.RequestAuthenticator, 0, packetBytesArrayCopy, 4, 16);
                var temp = new Byte[16];
                Buffer.BlockCopy(temp, 0, packetBytesArrayCopy, messageAuthenticatorPosition + 2, 16);
                var messageAuthenticatorBytes = CalculateMessageAuthenticator(packetBytesArrayCopy, packet.SharedSecret);
                Buffer.BlockCopy(messageAuthenticatorBytes, 0, packetBytesArray, messageAuthenticatorPosition + 2, 16);
            }

            if (packet.Code == PacketCode.AccountingRequest || packet.Code == PacketCode.DisconnectRequest || packet.Code == PacketCode.CoaRequest)
            {
                var authenticator = CalculateRequestAuthenticator(packet.SharedSecret, packetBytesArray);
                Buffer.BlockCopy(authenticator, 0, packetBytesArray, 4, 16);
            }
            else
            {
                var authenticator = packet.RequestAuthenticator != null ? CalculateResponseAuthenticator(packet.SharedSecret, packet.RequestAuthenticator, packetBytesArray) : packet.Authenticator;
                Buffer.BlockCopy(authenticator, 0, packetBytesArray, 4, 16);
            }
            
            return packetBytesArray;`

Let me know if you have questions--
Ben

**Comment by vforteli** [comment]
Hi, yup it does seem like this has been lurking here for a while, thanks for the heads up. Fix on its way

**Comment by co2chicken** [comment]
Thanks! That bug was learned the hard way :)
